function this = createGenotype(this)
    %this.createProgramInputs_(this.configuration_.config.structure.programInputs);
    this.createFunctionGenes_(this.configuration_.config.structure.functionGenes, this.configuration_.config.sizes.functions, this.configuration_.config.sizes.inputs);
    this.createConnectionGenes_(this.configuration_.config.structure, this.configuration_.config.sizes);
    this.createParameters_(this.configuration_.config.sizes, this.configuration_.parameters);
    this.createProgramOutputs_(this.configuration_.config.sizes.genes, this.configuration_.config.sizes.outputs, this.configuration_.config.sizes.nodes, this.configuration_.config.last_node_output);

    this.activeNodes_ = this.findActiveNodes_(this.configuration_.config.sizes, this.configuration_.config.structure.connectionGenes);

    this.fitness_ = cgptoolbox.Fitness(struct( ...
        'fitness_function', this.configuration_.config.fitness_function, ...
        'config', this.configuration_.config, ...
        'genes', this.genes_, ...
        'activeNodes', this.activeNodes_, ...
        'programInputs', this.configuration_.programInputs, ...
        'functionSet', {this.configuration_.functionSet}, ...
        'run', this.configuration_.config.run, ...
        'generation', this.configuration_.config.generation ...
    ));
end

