cgp = cgptoolbox.CGP(struct( ...
	'rows', 1, ...
	'columns', 20, ...
	'levels_back', 20, ...
	'last_node_output', true, ...
	'runs', 1, ...
	'outputs', 1, ...
	'generations', 5000, ...
	'population', 4, ...
	'mutation', 0.1, ...
	'best_fitness', 1 ...
));

x0 = zeros(1, 50);
y0 = zeros(1, 50);
index = 1;
for x = -1:0.04:1
    y0(index) = x^6 - 2*x^4 + x^2;
    x0(index) = x;
    index = index + 1;
end

input = struct('x0', x0, 'y0', y0);

cgp.addInputs( ...
    struct( ...
        'first', input, ...
        'second', 1 ...
    ) ...
);

cgp.addParameters( ...
	struct(                                ...
		'name', 'interval',                ...
		'initialize', @()rand(),           ...
		'mutate', @(x)rand()               ...
	) ...
);

cgp.addFunctionsFromPath('function-set/');
cgp.addFitnessFunction(@fitness);

cgp.train();
